/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as EspaceRouteImport } from './routes/espace'
import { Route as EspaceIndexRouteImport } from './routes/espace/index'
import { Route as EspaceJournalRouteImport } from './routes/espace/journal'
import { Route as EspaceReferentielsRouteImport } from './routes/espace/referentiels'
import { Route as EspaceUtilisateursRouteImport } from './routes/espace/utilisateurs'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiFichiersIdRouteImport } from './routes/api/fichiers/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const EspaceRoute = EspaceRouteImport.update({
  id: '/espace',
  path: '/espace',
  getParentRoute: () => rootRouteImport,
} as any)
const EspaceIndexRoute = EspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EspaceRoute,
} as any)
const EspaceJournalRoute = EspaceJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => EspaceRoute,
} as any)
const EspaceReferentielsRoute = EspaceReferentielsRouteImport.update({
  id: '/referentiels',
  path: '/referentiels',
  getParentRoute: () => EspaceRoute,
} as any)
const EspaceUtilisateursRoute = EspaceUtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => EspaceRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFichiersIdRoute = ApiFichiersIdRouteImport.update({
  id: '/api/fichiers/$id',
  path: '/api/fichiers/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/espace': typeof EspaceRouteWithChildren
  '/espace/journal': typeof EspaceJournalRoute
  '/espace/referentiels': typeof EspaceReferentielsRoute
  '/espace/utilisateurs': typeof EspaceUtilisateursRoute
  '/espace/': typeof EspaceIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/fichiers/$id': typeof ApiFichiersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/espace/journal': typeof EspaceJournalRoute
  '/espace/referentiels': typeof EspaceReferentielsRoute
  '/espace/utilisateurs': typeof EspaceUtilisateursRoute
  '/espace': typeof EspaceIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/fichiers/$id': typeof ApiFichiersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/espace': typeof EspaceRouteWithChildren
  '/espace/journal': typeof EspaceJournalRoute
  '/espace/referentiels': typeof EspaceReferentielsRoute
  '/espace/utilisateurs': typeof EspaceUtilisateursRoute
  '/espace/': typeof EspaceIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/fichiers/$id': typeof ApiFichiersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connexion'
    | '/espace'
    | '/espace/journal'
    | '/espace/referentiels'
    | '/espace/utilisateurs'
    | '/espace/'
    | '/api/auth/$'
    | '/api/fichiers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connexion'
    | '/espace/journal'
    | '/espace/referentiels'
    | '/espace/utilisateurs'
    | '/espace'
    | '/api/auth/$'
    | '/api/fichiers/$id'
  id:
    | '__root__'
    | '/'
    | '/connexion'
    | '/espace'
    | '/espace/journal'
    | '/espace/referentiels'
    | '/espace/utilisateurs'
    | '/espace/'
    | '/api/auth/$'
    | '/api/fichiers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnexionRoute: typeof ConnexionRoute
  EspaceRoute: typeof EspaceRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiFichiersIdRoute: typeof ApiFichiersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espace': {
      id: '/espace'
      path: '/espace'
      fullPath: '/espace'
      preLoaderRoute: typeof EspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espace/': {
      id: '/espace/'
      path: '/'
      fullPath: '/espace/'
      preLoaderRoute: typeof EspaceIndexRouteImport
      parentRoute: typeof EspaceRoute
    }
    '/espace/journal': {
      id: '/espace/journal'
      path: '/journal'
      fullPath: '/espace/journal'
      preLoaderRoute: typeof EspaceJournalRouteImport
      parentRoute: typeof EspaceRoute
    }
    '/espace/referentiels': {
      id: '/espace/referentiels'
      path: '/referentiels'
      fullPath: '/espace/referentiels'
      preLoaderRoute: typeof EspaceReferentielsRouteImport
      parentRoute: typeof EspaceRoute
    }
    '/espace/utilisateurs': {
      id: '/espace/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/espace/utilisateurs'
      preLoaderRoute: typeof EspaceUtilisateursRouteImport
      parentRoute: typeof EspaceRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fichiers/$id': {
      id: '/api/fichiers/$id'
      path: '/api/fichiers/$id'
      fullPath: '/api/fichiers/$id'
      preLoaderRoute: typeof ApiFichiersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EspaceRouteChildren {
  EspaceJournalRoute: typeof EspaceJournalRoute
  EspaceReferentielsRoute: typeof EspaceReferentielsRoute
  EspaceUtilisateursRoute: typeof EspaceUtilisateursRoute
  EspaceIndexRoute: typeof EspaceIndexRoute
}

const EspaceRouteChildren: EspaceRouteChildren = {
  EspaceJournalRoute: EspaceJournalRoute,
  EspaceReferentielsRoute: EspaceReferentielsRoute,
  EspaceUtilisateursRoute: EspaceUtilisateursRoute,
  EspaceIndexRoute: EspaceIndexRoute,
}

const EspaceRouteWithChildren =
  EspaceRoute._addFileChildren(EspaceRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnexionRoute: ConnexionRoute,
  EspaceRoute: EspaceRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiFichiersIdRoute: ApiFichiersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
